esphome:
  name: esp32-test
  includes: 
    - esp32_internal_temp.h

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "XXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  ota: off
  
sensor:    
  - platform: custom
    lambda: |-
      auto my_sensor = new esp32inttemp();
      App.register_component(my_sensor);
      return {my_sensor};

    sensors:
      name: "ESP32 cam internal temp"
      unit_of_measurement: °C
